# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll to S3 and CloudFront

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Deployment job
  deploy-s3:
    
    runs-on: ubuntu-latest
    # Allow write on id-token so we can use it to authenticate to AWS
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      
      # Generate index.md
      - run: cat .index-header.md README.md > index.md
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::584344484091:role/docs-takamatsu-fact-com-github-actions-deploy-v1
          aws-region: ap-northeast-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./_site s3://docs-takamatsu-fact-com-frontend-v1 \
            --delete \
            --cache-control "public,max-age=60" \

          aws cloudfront create-invalidation --distribution-id "E2MOC45M3QFEEU" --paths "/*"
